"""initial

Revision ID: fa79aeb78d8e
Revises: 
Create Date: 2025-06-09 16:21:02.803348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa79aeb78d8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SavedRow', 'Error', 'NotValid', 'Success', name='filestatus').create(op.get_bind())
    op.create_table('user_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hex_token', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('files', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('SavedRow', 'Error', 'NotValid', 'Success', name='filestatus', create_type=False), nullable=True),
    sa.Column('user_token_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_token_id'], ['user_token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_user_token_id'), 'research', ['user_token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_user_token_id'), table_name='research')
    op.drop_table('research')
    op.drop_table('user_token')
    sa.Enum('SavedRow', 'Error', 'NotValid', 'Success', name='filestatus').drop(op.get_bind())
    # ### end Alembic commands ###
